
import { Inter } from 'next/font/google'
import './globals.css'
import { Montserrat } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import CursorEffect from '@/components/CursorEffect'
import { ToastContainer } from 'react-toastify'
const inter = Inter({ subsets: ['latin'] })
import 'react-toastify/dist/ReactToastify.css'


const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont"
})

export const metadata = {
  title: 'Portfolio | Tejas Patel',
  description: 'Generated by create next app',
}




export default function RootLayout({ children }) {
  const mouseMove = () => {
    const cursorDot = document.querySelector("[data-cursor-dot]")
    const cursorOutline = document.querySelector("[data-cursor-outline]")

    window.addEventListener("mousemove", function (e) {
      const posX = e.clientX
      const posY = e.clientY

      cursorDot.style.left = `${posX}px`
      cursorDot.style.top = `${posY}px`

      cursorOutline.style.left = `${posX}px`
      cursorOutline.style.top = `${posY}px`
    })
  }
  return (
    <html lang="en">
      <body className={`${inter.className} ${montserrat.variable} bg-light dark:bg-dark  min-h-screen w-full font-mont`} >
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <Navbar />
        {/* <CursorEffect /> */}
        {children}
        <script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="techtez" data-description="Support me on Buy me a coffee!" data-message="" data-color="#FD0" data-position="Right" data-x_margin="18" data-y_margin="18"></script>
        <Footer />
      </body>
    </html>
  )
}
