import { Inter } from 'next/font/google'
import './globals.css'
import { Montserrat } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
const inter = Inter({ subsets: ['latin'] })

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont"
})

export const metadata = {
  title: 'Portfolio | Tejas Patel',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${montserrat.variable} bg-light dark:bg-dark  min-h-screen w-full font-mont`}>
        <Navbar />
        {children}
        <Footer />  
      </body>
    </html>
  )
}
