
import { Inter } from 'next/font/google'
import './globals.css'
import { Montserrat } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import CursorEffect from '@/components/CursorEffect'
import { ToastContainer } from 'react-toastify'
const inter = Inter({ subsets: ['latin'] })
import 'react-toastify/dist/ReactToastify.css'
import Layout from '@/components/Layout'


const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont"
})

export const metadata = {
  title: 'Portfolio | Tejas Patel',
  description: 'Generated by create next app',
}




export default function RootLayout({ children }) {
  const mouseMove = () => {
    const cursorDot = document.querySelector("[data-cursor-dot]")
    const cursorOutline = document.querySelector("[data-cursor-outline]")

    window.addEventListener("mousemove", function (e) {
      const posX = e.clientX
      const posY = e.clientY

      cursorDot.style.left = `${posX}px`
      cursorDot.style.top = `${posY}px`

      cursorOutline.style.left = `${posX}px`
      cursorOutline.style.top = `${posY}px`
    })
  }
  return (
    <html lang="en">
      <body className={`${inter.className} ${montserrat.variable} bg-light dark:bg-dark  min-h-screen w-full font-mont`} >
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <Navbar />
        {/* <CursorEffect /> */}
        {children}
        <div className='flex xs:flex-col mt-32 xs:mt-10 gap-10 xs:gap-5 sm:mt-10 font-mont max-w-5xl mx-32 mb-20 xs:mx-7'>
          <div className='w-full flex flex-col gap-5 xs:items-center'>
            <h1 className='xs:hidden inline-block text-dark dark:text-light font-bold xs:text-center capitalize text-5xl sm:text-3xl'>We got same taste? 😉</h1>
            <h3 className='text-left xs:text-center text-yellow-600 font-semibold text-xl'>Let the music play as you explore !.</h3>
          </div>
          <div className='w-full'>
            <iframe src="https://open.spotify.com/embed/playlist/1pWsZ0u92q0IjBIyGwHZOc?utm_source=generator&theme=0" width="100%" height="152" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  )
}
